### ISSUE TITLE
Enhancing User Experience by Generating Security Audit Reports in PDF, DOC, or TXT Formats

### ISSUE THREAD

**Issue by prayas7102** [prayas7102/NodejsSecurify#10]
Currently, the output of the NPM package is displayed in the VSCode terminal after running the required commands. However, for end users and developers (who downloads the NPM package), it would be more convenient if the security audit report could be generated as a PDF, DOC, or TXT file, allowing for easier review and avoiding the need to scroll through the terminal output.

Sample terminal report: 
[audit report.pdf](https://github.com/user-attachments/files/17230062/audit.report.pdf)

**Make sure the end user/developer (who downloads the NPM package) is able to smoothly run the NPM package after these changes.**

**Comment by eleensmathew** [comment]
Can I work on this?

**Comment by prayas7102** [comment]
> Can I work on this?

Sure, I've assigned you this issue.

**Comment by eleensmathew** [comment]
[NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17268828/NodeJsSecurifyReport.pdf)
Is this pdf okay?

**Comment by prayas7102** [comment]
> [NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17268828/NodeJsSecurifyReport.pdf) Is this pdf okay?

This pdf looks good, but at the end of pdf the result of 

> "Parsing for vulnerable npm pacakage"

 is not visible? Can you look into it?

**Comment by eleensmathew** [comment]
when i run src/NodeJsSecurify.js file I get this output in the terminal 
`******************************************************************************************
****************************** Node-Js-Securify STARTED **********************************
******************************************************************************************

Searching for .js files in (root directory) : /home/eleensmathew/NodejsSecurify/src

File names in .gitignore files not getting parsed: 

, Vulnerability, dist, NodeJsSecurify.js, node_modules

File path name of .js & .jsx files getting parsed: 

/home/eleensmathew/NodejsSecurify/src/GenerateReport.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 18


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/src/GenerateReport.ts
Error: Line 2: Unexpected token =
    at ErrorHandler.constructError (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.throwError (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:1936:34)
    at Parser.parseImportDeclaration (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:4837:23)
    at Parser.parseStatementListItem (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:3373:39)
    at Parser.parseScript (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:4723:29)
    at parse (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:122:61)
    at Object.parseScript (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:145:13)
    at Function.<anonymous> (/home/eleensmathew/NodejsSecurify/src/NodeJsSecurify.js:177:101)
    at step (/home/eleensmathew/NodejsSecurify/src/NodeJsSecurify.js:49:23) {
  index: 44,
  lineNumber: 2,
  description: 'Unexpected token ='
}
/home/eleensmathew/NodejsSecurify/src/NodeJsSecurify.ts
Error: Line 36: Unexpected token :
    at ErrorHandler.constructError (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.expect (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:2168:19)
    at Parser.parseFormalParameters (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:4274:23)
    at Parser.parseFunctionDeclaration (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:4337:38)
    at Parser.parseStatementListItem (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:3379:39)
    at Parser.parseFunctionSourceElements (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:4195:29)
    at Parser.isolateCoverGrammar (/home/eleensmathew/NodejsSecurify/node_modules/esprima/dist/esprima.js:2269:37) {
  index: 1407,
  lineNumber: 36,
  description: 'Unexpected token :'
}
Parsing for vulnerable npm pacakage:
Error executing npm audit: Command failed: npm audit --json
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm WARN audit 426 Upgrade Required - POST http://registry.npmjs.org/-/npm/v1/security/audits/quick
npm ERR! audit endpoint returned an error` all the errors not printed using console.log i am not outputing to the file. If you want me to include the messages printed in the terminal using console.error please let me know. Also if you can give me a test file to test the code with that would be better

**Comment by prayas7102** [comment]
> NodejsSecurify

i think you are giving the wrong path in NodeJsSecurify.ts:

![image](https://github.com/user-attachments/assets/2295cf9e-2eb8-4728-aaf3-30da51e5e018)

the correct path in `__dirname ` should be `/home/eleensmathew/NodejsSecurify/TestFolder`. Can u please try again with correct path ?

**Comment by prayas7102** [comment]
> include the messages printed in the terminal

ok in that case include the messages printed in the terminal too. And share the updated pdf.

**Comment by eleensmathew** [comment]
Updated pdf 
[NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17275920/NodeJsSecurifyReport.pdf)

```
******************************************************************************************
****************************** Node-Js-Securify STARTED **********************************
******************************************************************************************

Searching for .js files in (root directory) : /home/eleensmathew/NodejsSecurify/TestFolder
``
File names in .gitignore files not getting parsed: 

, Vulnerability, dist, NodeJsSecurify.js, node_modules

File path name of .js & .jsx files getting parsed: 

/home/eleensmathew/NodejsSecurify/TestFolder/BruteForceAttack/BruteForceNotVulnerable-1.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/BruteForceAttack/BruteForceVulnerable-1.js
==> No callback hell detected. Code looks good!


==> Code vulnerable to Brute force Attack in this file!!! 


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code vulnerable to Brute force Attack in this file!!! 


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHell-1.js
==> Callback hell detected! AT Line no. => 25 In file: CallBackHell-1.js
Make use of async/await or .then/.catch to avoid callback hell


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> Following dangerous function detected: 
> setTimeout detected at line: 1 Ensure: Remember to clear the interval when it's no longer needed: clearTimeout(timerId);
=====> Ignore above errors if you already made changes to your code <=====


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHell-10.js
==> Callback hell detected! AT Line no. => 34 In file: CallBackHell-10.js
Make use of async/await or .then/.catch to avoid callback hell


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> Following dangerous function detected: 
> setTimeout detected at line: 1 Ensure: Remember to clear the interval when it's no longer needed: clearTimeout(timerId);
=====> Ignore above errors if you already made changes to your code <=====


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHell-2.js
==> Callback hell detected! AT Line no. => 10 In file: CallBackHell-2.js
Make use of async/await or .then/.catch to avoid callback hell


==> Code vulnerable to Brute force Attack in this file!!! 


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code vulnerable to Brute force Attack in this file!!! 


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHell-4.js
==> Callback hell detected! AT Line no. => 6 In file: CallBackHell-4.js
Make use of async/await or .then/.catch to avoid callback hell


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> Following dangerous function detected: 
> setTimeout detected at line: 1 Ensure: Remember to clear the interval when it's no longer needed: clearTimeout(timerId);
=====> Ignore above errors if you already made changes to your code <=====


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHell-5.js
==> Callback hell detected! AT Line no. => 8 In file: CallBackHell-5.js
Make use of async/await or .then/.catch to avoid callback hell
==> Callback hell detected! AT Line no. => 10 In file: CallBackHell-5.js
Make use of async/await or .then/.catch to avoid callback hell


==> Code vulnerable to Brute force Attack in this file!!! 


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHell-7.js
==> Callback hell detected! AT Line no. => 4 In file: CallBackHell-7.js
Make use of async/await or .then/.catch to avoid callback hell


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> Following dangerous function detected: 
> getElementById detected at line: 1 Ensure: Regular expression to match only letters
=====> Ignore above errors if you already made changes to your code <=====


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHell-9.js
==> Callback hell detected! AT Line no. => 4 In file: CallBackHell-9.js
Make use of async/await or .then/.catch to avoid callback hell


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> Code vulnerable to Insecure Authentication in this file!!! 
Check for: Hardcoded Credentials, Weak Passwords, No Password Hashing, Insecure Session Management, Insecure Token Storage, Weak JWT Security


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHellNoError-3.js
==> No callback hell detected. Code looks good!


==> Code vulnerable to Brute force Attack in this file!!! 


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHellNoError-6.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/CallBackHell/CallBackHellNoError-8.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/DetectDangerousFunctions/DangerousFunctions-1.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 9


==> Code having proper input validation


==> Following dangerous function detected: 
> setTimeout detected at line: 1 Ensure: Remember to clear the interval when it's no longer needed: clearTimeout(timerId);
> parsedInt detected at line: 1 Ensure: Always specify the radix (base) to avoid unexpected results
> parsedFloat detected at line: 1 Ensure: Always specify the radix (base) to avoid unexpected results
> getElementById detected at line: 1 Ensure: Regular expression to match only letters
> outerHTML detected at line: 1 Ensure: It does'nt accepts script tag, can cause XSS Attack
> innerHTML detected at line: 1 Ensure: It does'nt accepts script tag, can cause XSS Attack
> document.write detected at line: 1 Ensure: Avoid using it to prevent DOM XSS attack
=====> Ignore above errors if you already made changes to your code <=====


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InputValidation/InputValidationError.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having improper input validation, vulnerable to DOS Attack:!!! 


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InputValidation/NoInputValidationError-1.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InputValidation/NoInputValidationError-2.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InputValidation/NoInputValidationError-3.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InputValidation/NoInputValidationError-4.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureAuthentication/InsecureAuthenticatio2.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> Following dangerous function detected: 
> JSON.parse detected at line: 1 Ensure: Be cautious about the source of the JSON data, Can lead to  Client-side JSON injection
=====> Ignore above errors if you already made changes to your code <=====


==> NO Insecure Authentication detected


==> Code vulnerable to Brute force Attack in this file!!! 


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureAuthentication/InsecureAuthentication1.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> Following dangerous function detected: 
> JSON.parse detected at line: 1 Ensure: Be cautious about the source of the JSON data, Can lead to  Client-side JSON injection
=====> Ignore above errors if you already made changes to your code <=====


==> NO Insecure Authentication detected


==> Code vulnerable to Brute force Attack in this file!!! 


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureAuthentication/InsecureAuthentication3.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureAuthentication/InsecureAuthentication4.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 4


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureAuthentication/InsecureAuthentication5.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureAuthentication/InsecureAuthentication6.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 4


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureAuthentication/InsecureAuthentication7.js
==> No callback hell detected. Code looks good!


==> Code vulnerable to Brute force Attack in this file!!! 


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureSecurityHeader/InsecureSecurityHeader1.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having improper input validation, vulnerable to DOS Attack:!!! 


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code vulnerable to Brute force Attack in this file!!! 


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureSecurityHeader/InsecureSecurityHeader2.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having improper input validation, vulnerable to DOS Attack:!!! 


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureSecurityHeader/InsecureSecurityHeader3.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having improper input validation, vulnerable to DOS Attack:!!! 


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code vulnerable to Brute force Attack in this file!!! 


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureSecurityHeader/InsecureSecurityHeader4.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having improper input validation, vulnerable to DOS Attack:!!! 


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/InsecureSecurityHeader/InsecureSecurityHeader5.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> NO RegExp object detected with ReDoS-prone patterns


==> Code having improper input validation, vulnerable to DOS Attack:!!! 


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/RegexAttack/RegexAttack1.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 2


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/RegexAttack/RegexAttack2.js
==> No callback hell detected. Code looks good!


==> Code vulnerable to Brute force Attack in this file!!! 


==> RegExp object detected with ReDoS-prone patterns at line 2


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/RegexAttack/RegexAttack3.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 2


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code vulnerable to Brute force Attack in this file!!! 


/home/eleensmathew/NodejsSecurify/TestFolder/RegexAttack/RegexAttack4.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 2


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/RegexAttack/RegexAttack5.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 2


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/RegexAttack/RegexAttack6.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 2


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


/home/eleensmathew/NodejsSecurify/TestFolder/RegexAttack/RegexAttack7.js
==> No callback hell detected. Code looks good!


==> Code NOT vulnerable to Brute force Attack


==> RegExp object detected with ReDoS-prone patterns at line 3


==> Code having proper input validation


==> No dangerous function detected


==> NO Insecure Authentication detected


==> Code NOT vulnerable to Brute force Attack


Parsing for vulnerable npm pacakage:
Error executing npm audit: Command failed: npm audit --json
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm WARN audit 426 Upgrade Required - POST http://registry.npmjs.org/-/npm/v1/security/audits/quick
npm ERR! audit endpoint returned an error
```

**Comment by eleensmathew** [comment]
Can i make the updated pull request?

**Comment by prayas7102** [comment]
> Can i make the updated pull request?

Sure.
